// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKVFad72-Px_5SwjHS4AThlzFRAQru0mk',
    appId: '1:964858635148:web:663faec6ea8e0192682ca9',
    messagingSenderId: '964858635148',
    projectId: 'social-media-chat-app-dc580',
    authDomain: 'social-media-chat-app-dc580.firebaseapp.com',
    storageBucket: 'social-media-chat-app-dc580.appspot.com',
    measurementId: 'G-0M5XE1N4B8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzMXCujSVs4I2rGw8XUdebsUJMJ4jIK0g',
    appId: '1:964858635148:android:fe2d59e27b1f500e682ca9',
    messagingSenderId: '964858635148',
    projectId: 'social-media-chat-app-dc580',
    storageBucket: 'social-media-chat-app-dc580.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEOyI5hyYTnFJ6RSjdoycJITbmT4aNqnw',
    appId: '1:964858635148:ios:995607d02233f3fc682ca9',
    messagingSenderId: '964858635148',
    projectId: 'social-media-chat-app-dc580',
    storageBucket: 'social-media-chat-app-dc580.appspot.com',
    iosBundleId: 'com.example.socialMediaChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEOyI5hyYTnFJ6RSjdoycJITbmT4aNqnw',
    appId: '1:964858635148:ios:995607d02233f3fc682ca9',
    messagingSenderId: '964858635148',
    projectId: 'social-media-chat-app-dc580',
    storageBucket: 'social-media-chat-app-dc580.appspot.com',
    iosBundleId: 'com.example.socialMediaChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKVFad72-Px_5SwjHS4AThlzFRAQru0mk',
    appId: '1:964858635148:web:23cdcd9d8fd5d513682ca9',
    messagingSenderId: '964858635148',
    projectId: 'social-media-chat-app-dc580',
    authDomain: 'social-media-chat-app-dc580.firebaseapp.com',
    storageBucket: 'social-media-chat-app-dc580.appspot.com',
    measurementId: 'G-YS4EFJ04W3',
  );
}
